use crate::loan_contract::LoanContract;

pub fn sample_contracts() -> Vec<LoanContract> {
    vec![
        LoanContract {
            contract_id: 1,
            borrower: "Alice".into(),
            amount: 8_000.0,
            interest_rate: 18.0,
            monthly_payment: 420.0,
            days_remaining: 120,
            loan_term_months: 6,
        },
        LoanContract {
            contract_id: 2,
            borrower: "Bob".into(),
            amount: 10_000.0,
            interest_rate: 17.5,
            monthly_payment: 530.0,
            days_remaining: 150,
            loan_term_months: 8,
        },
        LoanContract {
            contract_id: 3,
            borrower: "Carol".into(),
            amount: 15_000.0,
            interest_rate: 19.0,
            monthly_payment: 650.0,
            days_remaining: 180,
            loan_term_months: 12,
        },
        LoanContract {
            contract_id: 4,
            borrower: "Dave".into(),
            amount: 120_000.0,
            interest_rate: 10.0,
            monthly_payment: 2800.0,
            days_remaining: 900,
            loan_term_months: 36,
        },
        LoanContract {
            contract_id: 5,
            borrower: "Eve".into(),
            amount: 140_000.0,
            interest_rate: 11.0,
            monthly_payment: 3100.0,
            days_remaining: 850,
            loan_term_months: 48,
        },
        LoanContract {
            contract_id: 6,
            borrower: "Frank".into(),
            amount: 180_000.0,
            interest_rate: 9.5,
            monthly_payment: 3500.0,
            days_remaining: 1000,
            loan_term_months: 60,
        },
        LoanContract {
            contract_id: 7,
            borrower: "Grace".into(),
            amount: 500_000.0,
            interest_rate: 7.0,
            monthly_payment: 5500.0,
            days_remaining: 3500,
            loan_term_months: 240,
        },
        LoanContract {
            contract_id: 8,
            borrower: "Henry".into(),
            amount: 650_000.0,
            interest_rate: 6.5,
            monthly_payment: 6200.0,
            days_remaining: 4000,
            loan_term_months: 300,
        },
        LoanContract {
            contract_id: 9,
            borrower: "Ivy".into(),
            amount: 800_000.0,
            interest_rate: 6.0,
            monthly_payment: 7300.0,
            days_remaining: 4200,
            loan_term_months: 360,
        },
        LoanContract {
            contract_id: 10,
            borrower: "Jack".into(),
            amount: 50_000.0,
            interest_rate: 28.0,
            monthly_payment: 1500.0,
            days_remaining: 600,
            loan_term_months: 24,
        },
        LoanContract {
            contract_id: 11,
            borrower: "Kate".into(),
            amount: 65_000.0,
            interest_rate: 30.0,
            monthly_payment: 1700.0,
            days_remaining: 700,
            loan_term_months: 30,
        },
        LoanContract {
            contract_id: 12,
            borrower: "Luke".into(),
            amount: 55_000.0,
            interest_rate: 32.0,
            monthly_payment: 1650.0,
            days_remaining: 650,
            loan_term_months: 36,
        },
    ]
}
